### ISSUE TITLE
The logo overlaps the title

### ISSUE THREAD

**Issue by shiv-chan** [chingu-voyages/v35-geckos-team-08#16]
Because the logo has the absolute position, it overlaps the title at some point like the screenshot below. 
![スクリーンショット 2021-11-30 9 52 52](https://user-images.githubusercontent.com/51708229/144105603-33cfcea9-8bb2-4c16-83a5-4adc7ae8ecd1.png)

_Originally posted by @shiv-chan in https://github.com/chingu-voyages/v35-geckos-team-08/pull/15#pullrequestreview-819397942_

**Comment by shiv-chan** [comment]
@Shiho317 I tried to arrange the logo, the title, and the paragraph's position with `grid` for laptops and bigger-sized screens, but it didn't turn out to look well.
(I updated the HTML structure in order to do so. Please check the branch `feature-suggestion-top-page-responsive`. )

I suggest that we have the same design as the smaller screens for laptops as well. The logo is on the top of the title one.
This can make it easier and look nicer.
What do you think?

**Comment by Shiho317** [comment]
Thank you Kaho! 
I totally agree with that.
And I changed.
Thanks.
