### ISSUE TITLE
Menu items - hovered

### ISSUE THREAD

**Issue by shiv-chan** [chingu-voyages/v35-geckos-team-08#22]
![menu-hover](https://user-images.githubusercontent.com/51708229/147159357-fa8bd93d-e655-4a9f-bd89-5665b1b5dd9a.gif)

@Shiho317 As I mentioned in PR #21, the menu items have a redundant/longer underline like the capture.
Also, I noticed that the menu items' colour turns red as the colour of the menu background when it's hovered.

Could you please fix this issue and update the code?

It's great to refer to my code or suggestions and I appreciated that you applied them but they are not always perfect, so please check and test how it works yourself after changing some parts.

You can also re-assign the reviewers in PR when you update something so that we can test it as well.

Thanks!

**Comment by shiv-chan** [comment]
@Shiho317 @bluwakpa 
I think it's better to close the menu when clicking one of the items on the menu from a UX perspective.
While I was playing around on my mobile device I felt it's a bit of pain to close the menu every time...😫

What do you think?

**Comment by Shiho317** [comment]
Hi @shiv-chan !
Thank you for comment.
I fixed styles and good on my browser. I created PR for this changes.
So please check it from there.

**Comment by shiv-chan** [comment]
Solved in #27
