### ISSUE TITLE
The page position goes up when closing the keyboard - mobile devices

### ISSUE THREAD

**Issue by shiv-chan** [chingu-voyages/v35-geckos-team-08#25]
When trying to fill out the contact form in the Contact section on a mobile device, the page position goes up to the About section after closing the keyboard.

Sorry, I don't have the capture here, but you can check this issue on your mobile device.
You run the server on your local machine and put `<your IP address like 123.456.7.89>:3000` on the browser on your mobile device.

**Comment by Shiho317** [comment]
solved by PR#33
